################################# tenant #################################
GET http://localhost:4000/tenant
	?take=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJvdXNzYW1AZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2NzgwOTIzNzgsImV4cCI6MTY3ODY5NzE3OH0.329mRB2wkvxcKfvT_xbtos4gbf96HIPx7PI12rs0MO0

#################################


GET http://localhost:4000/tenant/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJvdXNzYW1AZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2NzgwOTIzNzgsImV4cCI6MTY3ODY5NzE3OH0.329mRB2wkvxcKfvT_xbtos4gbf96HIPx7PI12rs0MO0

#################################


POST http://localhost:4000/tenant
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJvdXNzYW1AZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2NzgwOTIzNzgsImV4cCI6MTY3ODY5NzE3OH0.329mRB2wkvxcKfvT_xbtos4gbf96HIPx7PI12rs0MO0

{ 
	"name": "medpharma",
	"parentId": 3
}
#################################

PATCH  http://localhost:4000/tenant/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJvdXNzYW1AZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2NzgwOTIzNzgsImV4cCI6MTY3ODY5NzE3OH0.329mRB2wkvxcKfvT_xbtos4gbf96HIPx7PI12rs0MO0

{
	"name": "digi-forge",
	"parentId": 3,
	"users": [
		{
			"id": 1,
			"role": "ADMIN"
		}
	]
}
#################################

PATCH  http://localhost:4000/tenant/1/add-user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJvdXNzYW1AZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2NzgwOTIzNzgsImV4cCI6MTY3ODY5NzE3OH0.329mRB2wkvxcKfvT_xbtos4gbf96HIPx7PI12rs0MO0


{
		"id": 1,
		"role": "USER"
}
################################# 

PATCH  http://localhost:4000/tenant/1/remove-user/
Content-Type: application/json

{
	"userId": 1
}
################################# 


################################# user #################################

