# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  containerPort: ""
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: __enabledIngress__
  host: __ingressHost__
  className: ""
  annotations:
    {}
    #kubernetes.io/ingress.class: nginx
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

certificate:
  enabled: __enabledCertificate__
  issuerRef:
    name: ""
    kind: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumeMounts: []

extraVolumes: []

envVars:
  - name: HTTP_PORT
    value: "3000"
  - name: GRPC_PORT
    value: "3001"
  - name: LISCENSE_SEVER_URL
    value: "digi-forge-license-backend-dev-grpc-svc:3001"
  - name: AUTH_SEVER_URL
    value: "digi-forge-auth-backend-dev-grpc-svc:5000"
  - name: DATABASE_URL
    value: "postgresql://__DB_DEV_USER__:__DB_DEV_PASSWD__@postgres-dev-postgresql.db-dev.svc.cluster.local:5432/__DB_DEV_NAME__?schema=public"

customPorts:
  - name: grpc
    containerPort: 3001
