FROM node:18-alpine

WORKDIR /app

ARG SERVER_URL

COPY package*.json .

RUN npm install --force
RUN npm install serve -g
COPY . .

ENV VITE_API_URL=${SERVER_URL}

RUN yarn build

EXPOSE 8081

CMD ["serve", "-s", "dist" , "-l", "tcp://0.0.0.0:8081"]