const alarmTypes = ["UPS", "TEMPERATURE AND HUMIDITY", "COOLING UNIT", "Monitor_IO", "IPDU_A", "IO_Module", "POWER METER"] as const;
const alarmLevels = ["Notice", "Notice", "Critical"] as const;
type AlarmType = (typeof alarmTypes)[number];
type AlarmLevel = (typeof alarmLevels)[number];

const alarmsMap: {
  [alarmType in AlarmType]: {
    [alarmName: string]: number;
  };
} = {
  UPS: {
    EPO: 3,
    "Rectifier Fault": 3,
    "Rectifier Over Temperature": 3,
    "Inverter Over temperature": 3,
    "Rectifier Over current": 3,
    "Auxiliary power 1 fault": 3,
    "Auxiliary power 2 fault": 3,
    "Input Thyristor failed": 3,
    "Discharge Thyristor failed": 3,
    "Charge Thyristor failed": 3,
    "Fan fault": 3,
    "Fan Power fault": 3,
    "DC Bus over voltage": 3,
    "DC Bus below voltage": 3,
    "DC bus unbalance": 3,
    "Mains Site Wiring Fault": 3,
    "Soft start failed": 3,
    "Input Neutral line missing": 3,
    "Battery reverse": 3,
    "No battery": 3,
    "P-Battery Charger fault": 3,
    "N-battery charger fault": 3,
    "Battery under voltage": 3,
    "Battery over voltage": 3,
    "Battery low pre-warning": 2,
    "Mains freq.abnormal": 3,
    "Mains volt.abnormal": 3,
    "Inverter fault": 3,
    "Inv.IGBT bridge shorted": 3,
    "Inverter Thyristor short": 3,
    "Inverter Thyristor broken": 3,
    "Bypass Thyristor short": 3,
    "Bypass Thyristor broken": 3,
    "CAN comm.Fault": 3,
    "Parallel load sharing fault": 3,
    "Bypass Site Wiring Fault": 3,
    "System Not Sync.To Bypass": 3,
    "Bypass unable to trace": 3,
    "Bypass Not Available": 3,
    "IGBT over current": 3,
    "Fuse broken": 3,
    "Cable connection error": 3,
    "Parallel relay fault": 3,
    "LBS Not SYNC": 3,
    "Initializtion fault": 3,
    "Inverter on invalid": 3,
    Overload: 3,
    "Parallel Overload": 3,
    "DC component over limit": 3,
    "Bypass over current": 3,
    "Feedback protection": 3,
    "BUS volt.abnormal": 3,
    "Battery Fault": 3,
    "Battery over temperature": 3,
    "Fire Alarm": 3,
    "Smoke Alarm": 3,
    "Machine Type Setting fault": 3,
    "Over Preventive Maintenance Time": 3,
    Dynamotor: 3,
    "INV.Off due to PowerOff": 3,
    "INV.Off due to Overload": 3,
    "Inverter invalid due to over load": 3,
    "UPS In shutdown Due To Overload.": 3,
    "UPS In Bypass Due To Overload": 3,
    "Parallel in Bypass": 3,
    "ShutDown Due To Batt.Low": 3,
    "Transfer Times-out": 3,
    "Rectifier fault": 3,
    "Auxiliary power fault": 3,
    "Invert Thyristor failed": 3,
    "bypass Thyristor failed": 3,
    "DC BUS volt.abnormal": 3,
    "Battery Thyristor failed": 3,
    "Charger fault": 3,
    "Parallel fault": 3,
    "Ext.Fire Alarm": 3,
    "Ext.Smoke Alarm": 3,
    "Communication state": 3,
  },
  "TEMPERATURE AND HUMIDITY": {
    "High Temperature State": 3,
    "Low Temperature State": 2,
    "High Humidity State": 2,
    "Low Humidity State": 2,
    "Communication State": 3,
  },
  "COOLING UNIT": {
    "Low Pressure": 2,
    "FAN Fault": 3,
    "Heater Overload": 3,
    "Filter Blocked": 2,
    "High Temperature": 3,
    "Low Temperature": 2,
    "High Humidity": 2,
    "Low Humidity": 2,
    "Compressor Run Overtime": 2,
    "Return Temp Sensor Fault/ Invalid": 3,
    "Supply Temp Sensor Fault/ Invalid": 3,
    "Indoor Humid Sensor Fault / Invalid": 2,
    "Pressure Sensor Fault / Invalid": 3,
    "Clock": 2,
    "High Pressure": 3,
    "Leakage": 3,
    "Water Flow": 2,
    "Network Break": 2,
    "Cold Water Cutoff": 3,
    "FAN1 Fault": 3,
    "FAN2 Fault": 3,
    "FAN3 Fault": 3,
    "Humidifier Fault": 3,
    "Return Temp Sensor Fault / Invalid": 3,
    "Cabinet Inlet Temp Sensor 1 Fault / Invalid": 2,
    "Cabinet Inlet Temp Sensor 2 Fault / Invalid": 2,
    "Cabinet Inlet Temp Sensor 3 Fault / Invalid": 2,
    "Cabinet Inlet Temp Sensor 4 Fault / Invalid": 2,
    "Cabinet Inlet Temp Sensor 5 Fault / Invalid": 2,
    "Cabinet Inlet Temp Sensor 6 Fault / Invalid": 2,
    "Smoke / Fire": 3,
    "Differential Pressure Switch": 2,
    "Condensated Water Overflow": 2,
    "High Pressure Switch": 2,
    "Exhaust Temp": 2,
    "Condenser Water Flow": 2,
    "Condenser": 2,
    "FAN4 Fault": 3,
    "FAN5 Fault": 3,
    "FAN6 Fault": 3,
    "Compressor Start Fail": 3,
    "Compressor Working Range": 2,
    "High Exhaust Temp(BLDC)": 2,
    "Low Differential Pressure": 2,
    "VF Offline": 2,
    "VF state": 2,
    "Suction Pressure Sensor S1 Fault": 3,
    "Suction Temp Sensor S2 Fault": 3,
    "Suction Pressure Sensor S3 Fault": 3,
    "Suction Temp Sensor S4 Fault": 3,
    "Low Superheat": 2,
    "Low Evaporating Temp": 2,
    "High Evaporating Temp": 2,
    "High Condensing Temp": 2,
    "Driver Memory Fault": 3,
    "Motor of EEV Fault": 3,
    "Driver Off Line": 2,
    "Low Suction Temp": 2,
    "EEV Driver Battery Fault": 3,
    "Low Suction Pressure": 2,
    "Compressor Need Maintenance": 2,
    "Heater Need Maintenance": 2,
    "FAN Need Maintenance": 2,
    "Humidifier Need Maintenance": 2,
    "Aircon State": 1,
    "Communication State": 3,
  },
  "Monitor_IO": {
    "Smoke": 3,
    "Water Leakage": 3,
    "Door": 1,
    "Communication state": 3,
  },
  "IPDU_A": {
    "Communication State": 3
  },
  "IO_Module": {
    "Communication State": 3,
  },
  "POWER METER": {
    "Communication State": 3,
  }
};
